eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  session:
    jdbc:
      schema: schema.sql
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090;
    driverName: org.h2.Driver
    username: sa
    password: null